@host = http://localhost:5000/api/account
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI4MzA3OTAsInR5cGUiOiJhY2Nlc3MiLCJfaWQiOiI2N2Q3ZWYyMjBiMzhlZDFiOWY5Mjk3YTYiLCJyb2xlIjoiYWRtaW4ifQ.B8ht5ALmY5c7Vs2-btvKc-nDOYpk5eUx2LZ98HTvYRI


### register - user
POST {{host}}/register
Content-Type: application/json

{
  "fullName": "Raj kumar",
  "email": "raj@gmail.com",
  "password": "12345678",
  "role": "user",
  "gender": "Male",
  "dob": "1999-07-16T12:22:00.000Z",
  "maritalStatus": "Single",
  "proffessionalDetails":{
    "highestQualification": "Master's",
    "qualifications": "B.Com, M.Com",
    "companyName": "TCS",
    "profession": "Software Engineer",
    "salary": 80030
  },
  "contactDetails":{
    "mobile": "1234567890",
    "address": "680 Nguyen Cliffs\nNew Amy, IL 82099"
  },
  "familyDetails": {
    "fatherName": "Aaron",
    "motherName": "Marissa",
    "noOfBrothers": 2,
    "noOfSisters": 2,
    "birthOrder": 1
  },
  "vedicHoroscope": {
    "rasi": "kanni",
    "lagna": "dhanusu",
    "nakshatra": "bharani",
    "dashaPeriod": "14 months",
    "placeofBirth": "Port Elizabethview",
    "timeOfBirth": "8:30 AM",
    "expectation": "nothing else",
    "raasiChart": {
      "house1": [{ "planet": "mars", "degree": 10 }],
      "house2": [{ "planet": "mercury", "degree": 20 }],
      "house3": [{ "planet": "venus", "degree": 30 }]
    },
    "navamsaChart": {
      "house1": [{ "planet": "mars", "degree": 10 }],
      "house2": [{ "planet": "mercury", "degree": 20 }],
      "house3": [{ "planet": "venus", "degree": 30 }]
    }
  },
  "partnerExpectation": {
    "maritalStatus": "Single"
  },
  "otherDetails": {
    "houseType": "own",
    "height": 180,
    "color": "brown"
  }
}


### register - broker | admin
POST {{host}}/register
Content-Type: application/json

{
  "fullName": "WhitneyPeterson",
  "email": "adminmy@gmail.com",
  "role": "admin",
  "password": "12345678",
  "address": "680 Nguyen Cliffs\nNew Amy, IL 82099"
}


### admin login
POST {{host}}/login
Content-Type: application/json

{
  "email": "adminmy@gmail.com",
  "password": "12345678",
  "role": "admin"
}


### user login
POST {{host}}/login
Content-Type: application/json

{
  "email": "raj@gmail.com",
  "password": "12345678",
  "role": "user"
}


### get access token using refresh token
POST {{host}}/access-token
Content-Type: application/json


### forget password
POST {{host}}/forgot-pass
Content-Type: application/json

{
  "email": "kent11@gmail.com",
  "role": "user"
}


### reset password
POST {{host}}/reset-pass
Content-Type: application/json

{
  "email": "kent11@gmail.com",
  "password": "12345678",
  "otp": 863776,
  "role": "user"
}


### upload register profile img
POST {{host}}/register-image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpg

< ./male.jpg
------WebKitFormBoundary--


### user details
GET {{host}}/check-approval-status
Authorization: {{token}}


### user details
GET {{host}}/me
Authorization: {{token}}


### logout
POST {{host}}/logout
Authorization: {{token}}
Content-Type: application/json
