@host = http://localhost:5000/api/admin
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDI4MzA3OTAsInR5cGUiOiJhY2Nlc3MiLCJfaWQiOiI2N2Q3ZWYyMjBiMzhlZDFiOWY5Mjk3YTYiLCJyb2xlIjoiYWRtaW4ifQ.B8ht5ALmY5c7Vs2-btvKc-nDOYpk5eUx2LZ98HTvYRI


### users list ---- skip=6&limit=8&approvalStatus=["pending","rejected"]&ageRange=below_25&salaryRange=20000_30000
GET {{host}}/users?approvalStatus=approved
Authorization: {{token}}


### married users
GET {{host}}/users/married
Authorization: {{token}}


### create users
POST {{host}}/users
Authorization: {{token}}
Content-Type: application/json

[
  {
    "fullName": "WhitneyPeterson",
    "email": "raj4@gmail.com",
    "password": "12345678",
    "role": "user",
    "gender": "Male",
    "dob": "1950-07-16T12:22:00.000Z",
    "maritalStatus": "Single",
    "proffessionalDetails":{
      "highestQualification": "Bachelor's",
      "qualifications": "bcom",
      "companyName": "TCS",
      "profession": "Doctor",
      "salary": 80030
    },
    "contactDetails":{
      "mobile": "1234567890",
      "address": "680 Nguyen Cliffs\nNew Amy, IL 82099"
    },
    "familyDetails": {
      "fatherName": "Aaron",
      "motherName": "Marissa",
      "noOfBrothers": 2,
      "noOfSisters": 2,
      "birthOrder": 1
    },
    "vedicHoroscope": {
      "rasi": "kanni",
      "lagna": "dhanusu",
      "nakshatra": "bharani",
      "dashaPeriod": "14 months",
      "placeofBirth": "Port Elizabethview",
      "timeOfBirth": "8:30 AM",
      "expectation": "nothing else",
      "raasiChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      },
      "navamsaChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      }
    },
    "partnerExpectation": {
      "maritalStatus": "Single"
    },
    "otherDetails": {
      "houseType": "own",
      "height": 180,
      "color": "brown"
    }
  },
  {
    "fullName": "WhitneyPeterson",
    "email": "raj@gmail.com",
    "password": "12345678",
    "role": "user",
    "gender": "Male",
    "dob": "1950-07-16T12:22:00.000Z",
    "maritalStatus": "Single",
    "proffessionalDetails":{
      "highestQualification": "Bachelor's",
      "qualifications": "bcom",
      "companyName": "company",
      "profession": "Doctor",
      "salary": 80030
    },
    "contactDetails":{
      "mobile": "1234567890",
      "address": "680 Nguyen Cliffs\nNew Amy, IL 82099"
    },
    "familyDetails": {
      "fatherName": "Aaron",
      "motherName": "Marissa",
      "noOfBrothers": 2,
      "noOfSisters": 2,
      "birthOrder": 1
    },
    "vedicHoroscope": {
      "rasi": "kanni",
      "lagna": "dhanusu",
      "nakshatra": "bharani",
      "dashaPeriod": "14 months",
      "placeofBirth": "Port Elizabethview",
      "timeOfBirth": "8:30 AM",
      "expectation": "nothing else",
      "raasiChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      },
      "navamsaChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      }
    },
    "partnerExpectation": {
      "maritalStatus": "Single"
    },
    "otherDetails": {
      "houseType": "own",
      "height": 180,
      "color": "brown"
    }
  }
]


### user married to
POST {{host}}/user/married-to
Authorization: {{token}}
Content-Type: application/json

{
  "_id": "67df9a42fea06db4108cf3b3",
  "marriedTo": "67df9a42fea06db4108cf449"
}


### update user details
PUT {{host}}/user
Authorization: {{token}}
Content-Type: application/json

{
  "_id": "67df9b53f94b40ab3bae5cfa",
  "approvalStatus": "approved"
}
