@host = http://localhost:5000/api/admin
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NlNzE3YTFhNmYwNDkwMTQ5MWM0ZTAiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDE5MjU2NzF9.ODxmPil93Y9D1LUvnadebTEUFX2QwIDhyMFoIe5Ui4Q


### users list ---- skip=6&limit=8&approvalStatus=["pending","rejected"]&ageRange=below_25&salaryRange=20000_30000
GET {{host}}/users?approvalStatus=pending&limit=200
Authorization: {{token}}


### create users
POST {{host}}/users
Authorization: {{token}}
Content-Type: application/json

[
  {
    "fullName": "WhitneyPeterson",
    "email": "raj4@gmail.com",
    "password": "12345678",
    "role": "user",
    "gender": "Male",
    "dob": "1950-07-16T12:22:00.000Z",
    "maritalStatus": "Single",
    "proffessionalDetails":{
      "qualification": "bcom",
      "salary": 80030,
      "work": "education"
    },
    "contactDetails":{
      "mobile": "1234567890",
      "address": "680 Nguyen Cliffs\nNew Amy, IL 82099"
    },
    "familyDetails": {
      "fatherName": "Aaron",
      "motherName": "Marissa",
      "noOfBrothers": 2,
      "noOfSisters": 2,
      "birthOrder": 1
    },
    "vedicHoroscope": {
      "rasi": "kanni",
      "lagna": "dhanusu",
      "nakshatra": "bharani",
      "dashaPeriod": "14 months",
      "placeofBirth": "Port Elizabethview",
      "timeOfBirth": "8:30 AM",
      "expectation": "nothing else",
      "raasiChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      },
      "navamsaChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      }
    },
    "partnerExpectation": {
      "maritalStatus": "Single",
      "qualification": "bcom",
      "work": "education"
    },
    "otherDetails": {
      "houseType": "own",
      "height": 180,
      "color": "brown"
    }
  },
  {
    "fullName": "WhitneyPeterson",
    "email": "raj@gmail.com",
    "password": "12345678",
    "role": "user",
    "gender": "Male",
    "dob": "1950-07-16T12:22:00.000Z",
    "maritalStatus": "Single",
    "proffessionalDetails":{
      "qualification": "bcom",
      "salary": 80030,
      "work": "education"
    },
    "contactDetails":{
      "mobile": "1234567890",
      "address": "680 Nguyen Cliffs\nNew Amy, IL 82099"
    },
    "familyDetails": {
      "fatherName": "Aaron",
      "motherName": "Marissa",
      "noOfBrothers": 2,
      "noOfSisters": 2,
      "birthOrder": 1
    },
    "vedicHoroscope": {
      "rasi": "kanni",
      "lagna": "dhanusu",
      "nakshatra": "bharani",
      "dashaPeriod": "14 months",
      "placeofBirth": "Port Elizabethview",
      "timeOfBirth": "8:30 AM",
      "expectation": "nothing else",
      "raasiChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      },
      "navamsaChart": {
        "house1": [{ "planet": "mars", "degree": 10 }],
        "house2": [{ "planet": "mercury", "degree": 20 }],
        "house3": [{ "planet": "venus", "degree": 30 }]
      }
    },
    "partnerExpectation": {
      "maritalStatus": "Single",
      "qualification": "bcom",
      "work": "education"
    },
    "otherDetails": {
      "houseType": "own",
      "height": 180,
      "color": "brown"
    }
  }
]


### update user details
PUT {{host}}/user
Authorization: {{token}}
Content-Type: application/json

{
  "_id": "67d2a217fd120a6d6dc14fa6",
  "approvalStatus": "approved"
}
