@host = http://localhost:5000/api/extractor
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUyMjgzMzAsInR5cGUiOiJhY2Nlc3MiLCJfaWQiOiI2N2Q3ZWYyMjBiMzhlZDFiOWY5Mjk3YTYiLCJyb2xlIjoiYWRtaW4ifQ.akD4gwdr1wGqFpqvz034RVviRP-70UnvpOcmegGP3WE

### extract image
POST {{host}}
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="sample1.jpg"
Content-Type: image/jpg

< ./sample1.jpg
------WebKitFormBoundary--
