@host = http://localhost:5000/api/super-admin
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzVG9rZW4iLCJleHAiOjE3NTk4MTU5MTAsIl9pZCI6IjY4OTQyZWRhYjRkYzlmYWIxZjRjMDI1OSIsInJvbGUiOiJzdXBlci1hZG1pbiJ9.S349MqtQOmBLR2_9onGzB8_5_4WBT1pb6ONfK9JVUZc


### paid users --- limit=4&skip=20
GET {{host}}/users/paid
Authorization: {{token}}


### assisted subscribed users --- limit=4&skip=20
GET {{host}}/users/assisted-subscribed
Authorization: {{token}}


### users all payments --- limit=4&skip=20
GET {{host}}/users/all-payments
Authorization: {{token}}


### users created by --- limit=4&skip=20
GET {{host}}/users/created-by?createdBy=68942a49660c9ca1bf10293c
Authorization: {{token}}


### users created per admin
GET {{host}}/users-stats/created-per-admin
Authorization: {{token}}


### users created today
GET {{host}}/users-stats/created?date=2025-10-07
Authorization: {{token}}


### admins
GET {{host}}/admins
Authorization: {{token}}


### create admin
POST {{host}}/admin
Authorization: {{token}}
Content-Type: application/json

{
  "fullName": "Vasan",
  "email": "vasan@admin.com",
  "password": "12345678"
}


### update admin
PUT {{host}}/admin/68942a49660c9ca1bf10293c
Authorization: {{token}}
Content-Type: application/json

{
  "fullName": "Vasan",
  "isDeleted": false
}
