@host = http://localhost:5000/api/user
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzNiNjBjYTRiMGVlZjMzM2ZmODc1YTMiLCJyb2xlIjoidXNlciIsImFwcHJvdmFsU3RhdHVzIjoicGVuZGluZyIsImV4cCI6MTczNTcwMjcwNH0.bLikWnZQvW_pTK9ksuQR9-XKE_1ZMgUxBm4QDzCujvE

### register
POST {{host}}/register
Content-Type: application/json

{
  "fullName": "WhitneyPeterson",
  "email": "adgagd@gmail.com",
  "password": "12345678",
  "gender": "male",
  "dob": "1950-07-16T12:22:00.000Z",
  "placeofBirth": "Port Elizabethview",
  "nakshatra": "bharani",
  "rasi": "kanni",
  "lagna": "dhanusu",
  "qualification": "bcom",
  "work": "education",
  "salary": 80030,
  "fatherName": "Aaron",
  "motherName": "Marissa",
  "noOfBrothers": 2,
  "noOfSisters": 2,
  "birthOrder": 1,
  "expectation": "nothing else",
  "formalities": "all",
  "houseType": "own",
  "address": "680 Nguyen Cliffs\nNew Amy, IL 82099",
  "dashaPeriod": "14 months",
  "height": 180,
  "color": "brown"
}


### login
POST {{host}}/login
Content-Type: application/json

{
  "email": "admin1@gmail.com",
  "password": "12345678"
}


### forget password
POST {{host}}/forgot-pass
Content-Type: application/json

{
  "email": "admin@gmail.com"
}


### reset password
POST {{host}}/reset-pass
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345678",
  "otp": 546836
}


### user details
GET {{host}}/me
Authorization: {{token}}


### logout
POST {{host}}/logout
Authorization: {{token}}
Content-Type: application/json


### upload img
PUT {{host}}/imgupload
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary--


### user details
GET {{host}}/673b60ca4b0eef333ff875a3
Authorization: {{token}}


### getMathces
GET {{host}}/matches?gender=female
Authorization: {{token}}


