@host = http://localhost:5000/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjcyYTVjZDAxOWVkZGY0NjVlNmQ2MTAiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxODc4OTcxOCwiZXhwIjoxNzE4ODU0NTE4fQ.udJEsalwX21tO-clWbe91OWKPq0rQdR-iAJs6wiYN_I

### register
POST {{host}}/register
Content-Type: application/json

{
  "fullName": "raj",
  "email": "raj6@gmail.com",
  "password": "aA1!aa",
  "gender": "male",
  "dob": "21/06/2002 10:10 AM",
  "placeofBirth": "viralimalai",
  "nakshatra": "nagam",
  "rasi": "thulam",
  "lagna": "mirugam",
  "qualification": "bsc",
  "work": "it",
  "salary": 25000,
  "fatherName": "nallu",
  "motherName": "angali",
  "noOfBrothers": 1,
  "noOfSisters": 2,
  "birthOrder": 2,
  "expectation": "nothing else",
  "formalities": "all",
  "houseType": "own",
  "address": "chennai",
  "dashaPeriod": "4months",
  "height": "180",
  "color": "white"
}

### login
POST {{host}}/login
Content-Type: application/json

{
  "email": "raj6@gmail.com",
  "password": "aA1!aa"
}


### user details
GET {{host}}/me
Authorization: {{token}}


### logout
POST {{host}}/logout
Authorization: {{token}}

