@host = http://localhost:5000/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjYwMDJlNTdkYWFkMTIxYTIzODBlNzIiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNzU4NTc2NCwiZXhwIjoxNzE3NjUwNTY0fQ.Chc7xoZjCeSPXGaihM26MFjhZ-R7bOcHgyU6JySvOAM

### register
POST {{host}}/register
Content-Type: application/json

{
  "fullName": "raj",
  "email": "rajq@gmail.com",
  "password": "aA1!aa",
"sex": "male",
  "dateofBirth": "21/06/2002",
  "timeofBirth": "10:10",
  "placeofBirth": "viralimalai",
  "nakshatra": "nagam",
  "rasi": "thulam",
  "lagna": "mirugam",
  "height": "180",
  "color": "white",
  "educationalQualification": "bsc",
  "work": "it",
  "salary": 25000,
  "fatherName": "nallu",
  "motherName": "angali",
  "brothers": 1,
  "sisters": 2,
  "birthOrder": 2,
  "expectation": "nothing else",
  "formalities": "all",
  "houseType": "own",
  "currentLiving": "chennai",
  "dashaPeriod": "4months",
}

### login
POST {{host}}/login
Content-Type: application/json

{
  "email": "rajq@gmail.com",
  "password": "aA1!aa"
}


### user details
GET {{host}}/me
Authorization: {{token}}


### logout
POST {{host}}/logout
Authorization: {{token}}

